spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mutantesdb
    username: "root"
    password: "root"
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate

  flyway:
    url: jdbc:mysql://localhost:3306/mutantesdb
    schemas: mutantesdb
    user: "root"
    password: "root"
    enabled: true
    outOfOrder: true
    locations: classpath:/db/migration/